name: Mirror to second repo

on:
  push:
    branches:
      - main  # اگر اسم برنچت چیز دیگه‌ایه مثل master یا dev، تغییر بده

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Clone source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to mirror repo
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote add mirror https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/TheRedBull071/SarTraderBot.git
          git push --mirror mirror
